# Generated by Django 2.2.16 on 2022-08-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220815_0240'),
        ('users', '0002_auto_20220815_1011'),
    ]

    operations = [
    ]
